[package]
name = "dfr-io-hat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.7"
linux-embedded-hal = "0.3.0"
tokio = { version = "1.29.1", features = ['time'] }
