[package]
name = "dfr-io-hat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
i2c-linux = "^0.1.2"

[[example]]
name = "blink"
path = "examples/blink.rs"
